name: "Push secrets from 1Password to Github Actions"

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - "gha-push-secrets-*"
  workflow_dispatch:
  pull_request:
    paths:
      - sync-secrets-to-gha/*

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  push-github-secrets:
    name: "Push Github Secret"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@9a0c9dd934086b7ab1d90115d455bda1c53c2bdb # v2.0.2

      - name: Load GH token
        id: op-gh-token
        uses: 1password/load-secrets-action@8d0d610af187e78a2772c2d18d627f4c52d3fbfb # v3.1.0
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://pulumi/gh-pulumi-runner-token/credential

      - uses: pulumi/auth-actions@1c89817aab0c66407723cdef72b05266e7376640 # v1.0.1
        with:
          organization: conda-forge
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:conda-forge-bot

      - uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58 # v6.6.1
        with:
          command: ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
          refresh: true
          stack-name: conda-forge/sync-secrets-gha/secrets
          work-dir: "./sync-secrets-gha"
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: ${{ steps.op-gh-token.outputs.GITHUB_TOKEN }}
